branches:
  - main
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - - '@semantic-release/git':
      assets:
        - CHANGELOG.md
        - README.md
        - .github/build/raspios-bullseye.img.xz
  - '@semantic-release/github'
