[env]
_.python.venv = { path = ".venv", create = true }

[tools]
consul = "1.22.7"
python = "3.14.8"
uv = "latest"
node = "24"
packer = "1.15.0"
prek = "latest"
vault = "2.1.1"

[tasks]
install_deps = "uv pip install ansible-core ansible-lint detect-secrets"
