[env]
_.python.venv = { path = ".venv", create = true }

[tools]
consul = "2.0.4"
python = "3.14"
uv = "0.12.23"
packer = "1.16.1"
prek = "0.5.5"
vault = "2.1.1"

[tasks]
install_deps = "uv pip install ansible-core ansible-lint detect-secrets"
