---
# tasks for configuring Consul
- name: Template server config
  become: true
  ansible.builtin.template:
    src: etc/consul.d/server.hcl.j2
    dest: "{{ consul_config_dir }}/server.hcl"
    owner: consul
    group: consul
    mode: 0640
    variable_start_string: "[["
    variable_end_string: "]]"
    force: true
  notify: Reload consul

- name: Template agent configuration
  become: true
  ansible.builtin.template:
    src: etc/consul.d/consul.hcl.j2
    dest: "{{ consul_config_dir }}/consul.hcl"
    owner: consul
    group: consul
    mode: 0640
    variable_start_string: "[["
    variable_end_string: "]]"
    # validate: consul validate %s

- name: Create scripts directory
  ansible.builtin.file:
    path: "{{ consul_data_dir }}/scripts"
    state: directory
    mode: 0700
    owner: consul
    group: consul

- name: Deliver Ansible bootstrap script
  ansible.builtin.copy:
    dest: "{{ consul_data_dir }}/scripts/ansible-bootstrap.sh"
    src: opt/consul/scripts/ansible-bootstrap.sh
    backup: true
    mode: 0700
    owner: consul
    group: consul
  tags:
    - watches

- name: Deliver Consul watches configuration
  ansible.builtin.template:
    dest: "{{ consul_config_dir }}/watches.hcl"
    src: etc/consul.d/watches.hcl.j2
    mode: 0644
    owner: consul
    group: consul
  tags:
    - watches

- name: Ensure not server when not server
  ansible.builtin.file:
    path: "{{ consul_config_dir }}/server.hcl"
    state: absent
  when: not is_server
