---
- name: Create scripts directory
  ansible.builtin.file:
    path: "{{ consul_data_dir }}/scripts"
    state: directory
    mode: 0700
    owner: consul
    group: consul

- name: Deliver Ansible bootstrap script
  ansible.builtin.copy:
    dest: "{{ consul_data_dir }}/scripts/ansible-bootstrap.sh"
    src: opt/consul/scripts/ansible-bootstrap.sh
    backup: true
    mode: 0700
    owner: consul
    group: consul
  tags:
    - watches

- name: Ensure not server when not server
  ansible.builtin.file:
    path: "{{ consul_config_dir }}/server.hcl"
    state: absent
  when: not is_server
