---
# tasks/launch-contained.yml
# Tasks responsible for launching consul in the relevant environment
- name: Launch | Get dumb-init
  ansible.builtin.package:
    name: dumb-init
    state: present

- name: Launch | Template startup script
  ansible.builtin.template:
    src: entrypoint.sh.j2
    dest: /entrypoint.sh
    mode: "0777"
    owner: root
    group: root
    force: true
    variable_start_string: "[["
    variable_end_string: "]]"
    # validate: shfmt %s
