---
# tasks to configure dns resolution
- name: Configure DNS servers
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^.*DNS=.*$'
    state: present
    line: "#DNS=100.100.100.100 1.1.1.1"
    backrefs: false
    insertafter: "^[Resolve]$"
    create: false
    backup: true
    firstmatch: true
    mode: "0644"
    owner: root
    group: root

- name: Configure DNS Search
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^.*Domains=.*$'
    state: present
    line: "#Domains=~orca-ordinal.ts.net"
    backrefs: false
    insertafter: "^.*DNS=.*$"
    create: false
    backup: true
    firstmatch: true
    mode: "0644"
    owner: root
    group: root


- name: Ensure resolveconf dir
  become: true
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d/
    state: directory
    mode: "0777"
    owner: root
    group: root
  tags:
    - resolved

# copy consul consul resolved configuration
- name: Template consul resolved configuration
  become: true
  ansible.builtin.template:
    dest: /etc/systemd/resolved.conf.d/consul.conf
    src: etc/systemd/resolved.conf.d/consul.conf.j2
    force: true
    mode: "0644"
    owner: systemd-resolve
    group: root
  notify: Restart resolved
  tags:
    - resolved

- name: Ensure stub directory
  ansible.builtin.file:
    path: /run/systemd/resolve/
    state: directory
    mode: "0777"
    owner: root
    group: root

- name: Template resolveconf stub
  ansible.builtin.template:
    dest: /run/systemd/resolve/stub-resolv.conf
    src: run/systemd/resolve/stub-resolv.conf.j2
    mode: "0644"
    owner: root
    group: root

- name: Check state of resolve.conf
  ansible.builtin.stat:
    path: /etc/resolv.conf
    follow: true
  register: resolvconf_stat

- name: Remove resolv.conf file
  when: resolveconf_stat.islnk is not defined
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: absent

- name: Ensure resolvconf is a symlink
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: link
    src: /run/systemd/resolve/stub-resolv.conf
    recurse: false

- name: Enable resolved
  become: true
  ansible.builtin.systemd:
    name: systemd-resolved
    enabled: true
    masked: false
  tags:
    - resolved

- name: Restart resolved
  become: true
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
  tags:
    - resolved
