---
- name: System | Template WPA Supplicant configuration
  ansible.builtin.template:
    src: etc/wpa_supplicant/wpa_supplicant.conf.j2
    dest: /etc/wpa_supplicant/wpa_supplicant.conf
    mode: "0644"
    owner: root
    group: root

- name: System | Set timezone
  community.general.timezone:
    name: "{{ timezone }}"
    hwclock: local

- name: System | Unblock rfkill
  ansible.builtin.command: rfkill unblock wifi
  changed_when: false

- name: System | Get all wlan rfkill configs
  ansible.builtin.find:
    paths: /var/lib/systemd/rfkill/
    patterns: "*wlan"
    file_type: file
    recurse: false
  register: wlan_rfkill_files

- name: System | Disable wlan rfkill # noqa: avoid-implicit
  ansible.builtin.copy:
    dest: "{{ item.path }}"
    content: 0
    force: true
    mode: "0644"
    owner: root
    group: root
  loop: "{{ wlan_rfkill_files.files }}"
