---
# Vault agent configuration
- name: Get Vault
  become: true
  ansible.builtin.unarchive:
    src: "{{ vault_zip_url }}"
    dest: /usr/bin/
    creates: /usr/bin/vault
    list_files: false
    keep_newer: false
    remote_src: true
    validate_certs: true
    mode: "0777"
    owner: root
    group: root

- name: Ensure Vault Agent configuration directory
  ansible.builtin.file:
    path: "{{ vault_agent_config_dir }}"
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Get Role id
  delegate_to: localhost
  become: false
  ansible.builtin.uri:
    url: "{{ lookup('env', 'VAULT_ADDR') }}/v1/auth/hashiatho.me/role/consul-secrets/role-id"
    method: GET
    return_content: true
    status_code: [200]
    headers:
      X-Vault-Token: "{{ lookup('env', 'VAULT_TOKEN') }}"
  register: role_id

- name: Deliver role id
  ansible.builtin.copy:
    dest: "{{ vault_agent_config_dir }}/vault_roleid"
    content: "{{ role_id.json.data.role_id }}"
    backup: true
    force: true
    mode: "0644"
    owner: root
    group: root

- name: Template Vault Agent template
  ansible.builtin.template:
    src: etc/vault-agent.hcl.j2
    dest: "{{ vault_agent_config_dir }}/vault-agent.hcl"
    backup: true
    mode: "0644"
    owner: root
    group: root

- name: Deliver agent templates
  ansible.builtin.template:
    dest: "{{ vault_agent_config_dir }}/{{ item.template }}.tmpl"
    src: "etc/vault.d/{{ item.template }}.tmpl.j2"
    backup: true
    mode: "0644"
    owner: root
    group: root
    variable_start_string: "[["
    variable_end_string: "]]"
  loop: "{{ vault_agent_templates }}"

- name: Systemd Unit
  when: not contained.stat.exists
  block:
    - name: Template Vault Agent systemd unit
      ansible.builtin.template:
        src: etc/systemd/system/vault-agent.service.j2
        dest: /etc/systemd/system/vault-agent.service
        backup: true
        mode: "0644"
        owner: root
        group: root
        # validate: systemd-analyze verify %s
      notify: Vault Agent Service

    - name: Enable Vault Agent service
      ansible.builtin.systemd:
        name: vault-agent
        state: restarted
        enabled: true
        masked: false
        daemon_reload: true
        daemon_reexec: true
        scope: system
        no_block: true
