---
- name: Deliver Consul watches configuration
  ansible.builtin.copy:
    dest: "{{ consul_config_dir }}/watches.hcl"
    src: etc/consul.d/watches.hcl
    mode: 0644
    owner: consul
    group: consul

- name: Start Consul watches
  ansible.builtin.template:
    src: etc/systemd/system/consul-watch.service.j2
    dest: /etc/systemd/system/consul-watch.service
    mode: 0644
    owner: root
    group: root
