---
# handlers file for ansible-role-template
- name: vault-agent-service
  ansible.builtin.systemd:
    name: vault-agent
    state: restarted
    enabled: true
    masked: false
    daemon_reload: true
    daemon_reexec: true
    scope: system
    no_block: true
