---
# handlers file for ansible-role-template
- name: Vault Agent Service
  ansible.builtin.systemd:
    name: vault-agent
    state: restarted
    enabled: true
    masked: false
    daemon_reload: true
    daemon_reexec: true
    scope: system
    no_block: true

- name: Reload consul
  ansible.builtin.command:
    cmd: consul reload
