---
name: main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Static Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint
        uses: ansible-community/ansible-lint-action@main
  secure:
    name: Security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Make results-dir
        run: mkdir -p results-dir
      - name: run kics Scan
        uses: checkmarx/kics-action@v1.5
        with:
          path: '.'
          output_path: results-dir
          output_formats: 'json,sarif'
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results-dir/results.sarif
  build:
    needs:
      - secure
      - lint
    name: Build Images
    permissions: write-all
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ".github/build/"
    strategy:
      matrix:
        target:
          - "docker-ubuntu.docker.ubuntu-amd64"
          - "docker-ubuntu.docker.ubuntu-arm64"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get Prerequisites
        run: |
          sudo apt-get install -y \
          binfmt-support \
          gzip \
          python3 \
          python3-pip \
          qemu \
          qemu-user-static
          unzip \
      - name: Add Ansible
        run: sudo -H pip3 install ansible
      - name: Get Packer
        run: |
          curl -fL https://releases.hashicorp.com/packer/1.8.2/packer_1.8.2_linux_amd64.zip | gunzip ->packer && \
          chmod u+x packer && \
          ./packer -version
      - name: Init Packer
        run: ./packer init .
      - name: Build Image
        shell: 'script -q -e -c "bash {0}"'
        run: |
          ./packer build \
            -var roles_path="${GITHUB_WORKSPACE}/../" \
            -var docker_password=${{ secrets.GITHUB_TOKEN }} \
            -only=${{ matrix.target }} \
            consul.pkr.hcl
  test:
    needs:
      - build
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Not yet
        run: echo "not implemented yet"
  release:
    needs:
      - secure
      - lint
      - build
      - test
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: add semantic release plugins
        run: |
          npm install -D '@semantic-release/changelog' \
                         '@semantic-release/github' \
                         '@semantic-release/git'

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
