---
# Push an image tagged with the latest version
# when a release is cut by semantic-release
name: Publish
on:
  release:
    types:
      - published
      - created
      - released
jobs:
  publish:
    strategy:
      matrix:
        target:
          - consul.docker.ubuntu-amd64
          - consul.arm.raspi-os-64
    name: Publish image version
    defaults:
      run:
        working-directory: .github/build/
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Mise en Place
        uses: jdx/mise-action@v2
        with:
          install: true
          experimental: true
          cache: true
      - name: Add deps
        run: |
          mise tasks run install_deps
      - name: Get Prerequisites
        run: |
          sudo apt-get install -y \
          binfmt-support \
          gzip \
          qemu-system \
          qemu-user-static
          unzip \
      - name: Init Packer
        run: pwd ; packer init .
      - name: Build Image (PR)
        shell: 'script -q -e -c "bash {0}"'
        run: |
          packer build \
            -var roles_path="${GITHUB_WORKSPACE}/../" \
            -var docker_password=${{ secrets.GITHUB_TOKEN }} \
            -var tag_version="${{ github.ref_name }}" \
            -only=${{ matrix.target }} \
            consul.pkr.hcl
