---
# Push an image tagged with the latest version
# when a release is cut by semantic-release
name: Publish
on:
  release:
    types:
      - published
      - created
      - released
jobs:
  publish:
    strategy:
      matrix:
        target:
          - "consul.docker.ubuntu.amd64"
          - "consul.docker.ubuntu.arm64"
    name: Publish image version
    defaults:
      run:
        working-directory: ".github/build/"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
        with:
          fetch-depth: 0
      - name: Get Prerequisites
        run: |
          sudo apt-get install -y \
          binfmt-support \
          gzip \
          python3 \
          python3-pip \
          qemu \
          qemu-user-static
          unzip \
      - name: Add Ansible
        run: sudo -H pip3 install ansible
      - name: Get Packer
        run: |
          curl -fL https://releases.hashicorp.com/packer/1.8.4/packer_1.8.4_linux_amd64.zip | gunzip ->packer && \
          chmod u+x packer && \
          ./packer -version
      - name: Init Packer
        run: pwd ; ./packer init .
      - name: Build Image (PR)
        shell: 'script -q -e -c "bash {0}"'
        run: |
          ./packer build \
            -var roles_path="${GITHUB_WORKSPACE}/../" \
            -var docker_password=${{ secrets.GITHUB_TOKEN }} \
            -var tag_version="${{ github.ref_name }}" \
            -only=${{ matrix.target }} \
            consul.pkr.hcl
